### ISSUE TITLE
document not found error in SSR

### ISSUE THREAD

**Issue by mohit-jasapara** [GuillaumeJasmin/react-table-hoc-fixed-columns#13]
Getting following error:

```
react-table-hoc-fixed-columns/lib/index.js:3234
var el = document.createElement('a');
         ^
ReferenceError: document is not defined
```

**Comment by GuillaumeJasmin** [comment]
Hi,
Please, you must provide better informations. Browser, package version...

`document` correspond to the `window.document` in your web browser. So technically, it's impossible to not have `document` .

**Comment by mohit-jasapara** [comment]
I am using latest Chrome version 69 and package version 1.0.1

The application is being rendered using Express node server and is not purely a client-side application.

So the library is relying on the browser's document variable in a place that runs before react actually mounts and the DOM is rendered.

So the file -> helper.js has the function enableStickyPosition which uses browser document before it is available.

```
var enableStickyPosition = function enableStickyPosition() {
  var el = document.createElement('a');
  var mStyle = el.style;
  mStyle.cssText = 'position:sticky;position:-webkit-sticky;position:-ms-sticky;';
  return mStyle.position.indexOf('sticky') !== -1;
};
```
One workaround I found is to **return true;** at the start of the above function after which the library works as intended. But it won't be able to support legacy browsers in that case.

**Comment by GuillaumeJasmin** [comment]
Thanks, I get it.
Effectively, for SSR, I must check if `window` object exist before use `document`.

However, how the browser will handle this ? One the server side, I can't check which version I must use, because I need a browser environment. So if the default choice is "sticky version", what is the behavior on the browser side if the browser can't support sticky position ? The DOM of "sticky position" and "scroll event" version are not the same, so the browser will recreate it ?

**Comment by GuillaumeJasmin** [comment]
fixed on `v1.0.3`

**Comment by otamnaz** [comment]
@GuillaumeJasmin Still getting document is not defined error.

`{ ReferenceError: document is not defined
at enableStickyPosition (node_modules/react-table-hoc-fixed-columns/lib/helpers.js:49:0)
at Object../node_modules/react-table-hoc-fixed-columns/lib/index.js (node_modules/react-table-hoc-fixed-columns/lib/index.js:28:0) ...`

`if (!document) return true; // document is undefined in SSR`

Using
- react-table: 6.9.0
- react-table-hoc-fixed-columns: 2.0.0
- next: 6.1.2

**Comment by GuillaumeJasmin** [comment]
Hi @otamnaz ,
Thanks for your feedback !
I do not use SSR, so I can't really test.

I just make this change https://github.com/GuillaumeJasmin/react-table-hoc-fixed-columns/commit/cc2b1b1666286c2c09db2e7049d6f117d61e24aa and I release it as `v2.0.1-alpha.1` .
Could you try, and tell me if that fix this bug ?
`react-table-hoc-fixed-columns@2.0.1-alpha.1`

Thanks !

**Comment by otamnaz** [comment]
Hi @GuillaumeJasmin 

Tested with `v2.0.1-alpha.1`, No error found!

**Comment by GuillaumeJasmin** [comment]
Thanks ! It's released as `v2.0.1`
